spring.application.name=Paymentservice

server.port=8088

# for local host
#spring.data.mongodb.uri=mongodb://testUser:testUser@localhost:27017/test

#for container. name should match with docker compose
spring.data.mongodb.uri=mongodb://testUser:testUser@mongodb:27017/test



security.basic.enabled=false
management.security.enabled=false

# Log at the root level
logging.level.root=INFO

# Log at the DEBUG level for a specific package
logging.level.com.example=DEBUG

# Output to a log file (optional)
logging.file.name=logs/payment.log

# Set log pattern (optional)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true


