apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-user.js: |
    db.createUser({
      user: "testUser",
      pwd: "testUser",
      roles: [
        {
          role: "readWrite",
          db: "test"
        }
      ]
    })
